# Generated by Django 5.0.3 on 2024-03-25 00:52

import django.utils.timezone
import django_quill.fields
import salekcodes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', salekcodes.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('content', django_quill.fields.QuillField()),
                (
                    'status',
                    models.CharField(choices=[('draft', 'Draft'), ('pub', 'Published')], default='draft', max_length=5),
                ),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', salekcodes.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={'abstract': False},
        ),
    ]
