# Generated by Django 5.2.16 on 2026-07-10 12:35

from django.db import migrations, models
from django.db.models import F


def backfill_published_at(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Post.objects.filter(status='pub', published_at__isnull=True).update(published_at=F('created_at'))


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_backfill_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_published_at, migrations.RunPython.noop),
    ]
